package guild

type FieldKey string

const (
	FieldKeyAFKChannelID                FieldKey = "afk_channel_id"
	FieldKeyAFKTimeout                  FieldKey = "afk_timeout"
	FieldKeyApplicationID               FieldKey = "application_id"
	FieldKeyApproximateMemberCount      FieldKey = "approximate_member_count"
	FieldKeyApproximatePresenceCount    FieldKey = "approximate_presence_count"
	FieldKeyBanner                      FieldKey = "banner"
	FieldKeyChannels                    FieldKey = "channels"
	FieldKeyDefaultMessageNotifications FieldKey = "default_message_notifications"
	FieldKeyDescription                 FieldKey = "description"
	FieldKeyDiscoverySplash             FieldKey = "discovery_splash"
	FieldKeyEmojis                      FieldKey = "emojis"
	FieldKeyExplicitContentFilter       FieldKey = "explicit_content_filter"
	FieldKeyFeatures                    FieldKey = "features"
	FieldKeyIcon                        FieldKey = "icon"
	FieldKeyIconHash                    FieldKey = "icon_hash"
	FieldKeyID                          FieldKey = "id"
	FieldKeyJoinedAt                    FieldKey = "joined_at"
	FieldKeyLarge                       FieldKey = "large"
	FieldKeyMaxMembers                  FieldKey = "max_members"
	FieldKeyMaxPresences                FieldKey = "max_presences"
	FieldKeyMaxVideoChannelUsers        FieldKey = "max_video_channel_users"
	FieldKeyMemberCount                 FieldKey = "member_count"
	FieldKeyMembers                     FieldKey = "members"
	FieldKeyMfaLevel                    FieldKey = "mfa_level"
	FieldKeyName                        FieldKey = "name"
	FieldKeyOwner                       FieldKey = "owner"
	FieldKeyOwnerID                     FieldKey = "owner_id"
	FieldKeyPermissions                 FieldKey = "permissions"
	FieldKeyPreferredLocale             FieldKey = "preferred_locale"
	FieldKeyPremiumSubscriptionCount    FieldKey = "premium_subscription_count"
	FieldKeyPremiumTier                 FieldKey = "premium_tier"
	FieldKeyPresences                   FieldKey = "presences"
	FieldKeyPublicUpdatesChannelID      FieldKey = "public_updates_channel_id"
	FieldKeyReason                      FieldKey = "reason"
	FieldKeyRegion                      FieldKey = "region"
	FieldKeyRoles                       FieldKey = "roles"
	FieldKeyRulesChannelID              FieldKey = "rules_channel_id"
	FieldKeySplash                      FieldKey = "splash"
	FieldKeySystemChannelFlags          FieldKey = "system_channel_flags"
	FieldKeySystemChannelID             FieldKey = "system_channel_id"
	FieldKeyUnavailable                 FieldKey = "unavailable"
	FieldKeyUser                        FieldKey = "user"
	FieldKeyVanityURLCode               FieldKey = "vanity_url_code"
	FieldKeyVerificationLevel           FieldKey = "verification_level"
	FieldKeyVoiceStates                 FieldKey = "voice_states"
	FieldKeyWidgetEnabled               FieldKey = "widget_enabled"
	FieldKeyWidgetChannelID             FieldKey = "widget_channel_id"
)
